### ISSUE TITLE
add "related software"

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgbackup.github.io#1]
Add such a section or navigation link list.

E.g.:
https://github.com/silvio/docker-borg

**Comment by anarcat** [comment]
docker-borg is 404 now.

**Comment by ThomasWaldmann** [comment]
oh. maybe the binaries are easier than docker. :)

maybe we could add atticmatic / borgmatic.

**Comment by anarcat** [comment]
this should either be moved to the main project (because that's where the site lives now) or closed..
