### ISSUE TITLE
Incorrect version information; 1.2.5→1.2.6

### ISSUE THREAD

**Issue by adlerweb** [borgbackup/borgbackup.github.io#104]
https://www.borgbackup.org/releases/
`Borg 1.2 is the current stable series of Borg. The current release is 1.2.5, released on 2023-08-30.`
Current stable is 1.2.6 released on 2023-08-31

**Comment by ThomasWaldmann** [comment]
Thanks for reporting this, fixed by:

https://github.com/borgbackup/borgbackup.github.io/commit/c3cb3a8938ce95bf9c6aea32132fed1ae04af9a9
