### ISSUE TITLE
Feed for releases?

### ISSUE THREAD

**Issue by enkore** [borgbackup/borgbackup.github.io#16]
Github provides a feed for releases (https://github.com/borgbackup/borg/releases.atom), which could be linked from the releases page.

**Comment by DrupaListo-com** [comment]
This page: https://github.com/borgbackup/borg/releases ?
Or the docs -> changelog page ?
Or both?

**Comment by enkore** [comment]
https://www.borgbackup.org/releases/

There is no way to edit the GitHub releases page.
