### ISSUE TITLE
commercial.html - Hetzner is also supporting borgbackup

### ISSUE THREAD

**Issue by Clevero** [borgbackup/borgbackup.github.io#28]
Hetzner is supporting borgbackup for their Storage Boxes

https://wiki.hetzner.de/index.php/BorgBackup/en#0._Activate_Borg_and_configure_your_storage_box

```For Borg to be enabled on your storage box, you must first enable the service on the Robot webinterface. To do this, go to the settings page of your storage box on the Robot webinterface and click "activate" on "Borg support"```

**Comment by jensens** [comment]
I can confirm this.  Borg at Hetzner Storage boxes works fine for us.

**Comment by ThomasWaldmann** [comment]
OK, someone make a PR.

Maybe link to /BorgBackup/en (without the anchor), so the link does not break if somebody edits the section title.

**Comment by ThomasWaldmann** [comment]
see #35
