### ISSUE TITLE
Suggestion to add pip dependencies

### ISSUE THREAD

**Issue by Wikinaut** [borgbackup/borgbackup.github.io#54]
On https://borgbackup.readthedocs.io/en/stable/installation.html#using-pip I suggest to add:

* pip install setuptools
* pip install cython

as these are essential for performing

* pip install borgbackup

then.

**Comment by ThomasWaldmann** [comment]
Wrong issue tracker (this is about the content of borgbackup.org), please move to that one:

https://github.com/borgbackup/borg/issues
