### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by samuel-w** [borgbackup/borgbackup.github.io#60]
Currently this repo is unlicensed, implying full copyright. I assume that the license should be the BSD-3 clause license, but it should be clear in the repo. https://github.com/borgbackup/borg-import/blob/master/LICENSE

**Comment by ThomasWaldmann** [comment]
correct!

**Comment by ThomasWaldmann** [comment]
could use same LICENSE file as borgbackup code repo, just the reference in there should point to AUTHORS via a full URL.
