### ISSUE TITLE
Data integrity error shown by extract dry run, after create and prune exit 0

### ISSUE THREAD

**Issue by marco-b-vlc2** [borgbackup/borgbackup.github.io#70]
## Environment
- Borgbackup 1.1.16, recently upgraded from 1.1.14 (that was a fresh-install, and suffered the same issue)
- OS RedHat EL8 virtual machines under KVM/OpenStack
- Filesystem is XFS, on top of CEPH provided by the same OpenStack (no CEPH issues observed across the other systems)

## Borg Backup architecture
- Each virtual machine (_data-vm_) runs Borgbackup where there are the data files, and do a remote backup over ssh to some another virtual machine (_repo-vm_) running the same Borgbackup version 1.1.16
- As soon as the backup is done, and exits 0 in the _data-vm_,  the prune is started in the _repo-vm_, and exits 0 too.
- Finally the _repo-vm_ starts the execution of ```borg extract --dry-run``` because we want to ensure repo consistency after each run (and before the repo is further rsynced)

## The issue
Sometimes (3 times in a couple of month) the ```borg extract --dry-run``` fails with the error below.

```
Data integrity error: Invalid segment entry size 0 - too small [segment 142, offset 37070417]

Traceback (most recent call last):
  File "borg/archiver.py", line 4690, in main
  File "borg/archiver.py", line 4622, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 192, in wrapper
  File "borg/archiver.py", line 805, in do_extract
  File "borg/archive.py", line 605, in extract_item
  File "borg/archive.py", line 251, in fetch_many
  File "borg/repository.py", line 1131, in get_many
  File "borg/repository.py", line 1125, in get
  File "borg/repository.py", line 1497, in read
  File "borg/repository.py", line 1524, in _read
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size 0 - too small [segment 142, offset 37070417]

Platform: Linux hostname.openstack.internal 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Wed Dec 16 03:30:52 EST 2020 x86_64
Linux: Red Hat Enterprise Linux 8.3 Ootpa
Borg: 1.1.16  Python: CPython 3.7.9 msgpack: 0.5.6.+borg1
PID: 700096  CWD: /home/bckadmin
sys.argv: ['borg', 'extract', '-v', '--dry-run', '/data/bck/bit::bit_20210715']
SSH_ORIGINAL_COMMAND: None
```

I've read that in most of the posts complaining about this issue the designated culprit is the block device, but i would like to resist that the CEPH is consistent..

**Comment by ThomasWaldmann** [comment]
Was that repo ever used with borg < 1.1.11? If so, read the changelog notes about 1.1.11.

**Comment by ThomasWaldmann** [comment]
I had a look at the source code of 1.1.16 and it looks to me that the data read was garbage (at least the size value was 0, although it can never be less than 41, as that is the size of the PUT entry header) - maybe the whole header was just all-zero?

That reminds of a bug that bit me many many years ago: back then we (IIRC) ran XFS on LVM on mdraid and there was some bug that made data not really end up on disk. So after some crash (or reboot?), a lot of files happened to have longer runs on all-zero content. It was a real pain. :-(

It could be also that a repo index entry points to an invalid location, so it would read data that is not really an entry header.

Guess you should transfer the repo contents to a reliable filesystem (like ext4 or zfs) and then run borg check on it and see if there is anything notable.

**Comment by marco-b-vlc2** [comment]
That repos were created by Borgbackup 1.1.14.
XFS conversion to ext4 is something that I'd like to try. I'll likely do this starting from half of the _repo-vm_ servers.
I'll need some time to plan and carry out the change, and there are holidays.
Maybe I'll not have updates on this very soon. Feel free to close the issue if you wish.
Many thanks!

**Comment by marco-b-vlc2** [comment]
But isn't it a "strange" corruption, either from memory, cpu, or storage to fill a file with a bunch of 0x00?
I'd expect just one (or few) bits or bytes of random/wrong data. That will also lead to hash cryptochecksum failure, but not to 125 0x00 bytes.

And what about: _will we loose all of the 1201 repo file content upon `check --repair`?_
That's also important to know, because we'll likely reduce the file size (at the cost of more files) if all the content will be lost.

We're running `borg check --verify-data` at this moment, to see the missing/corrupted file name, hoping that it may still be present in the original data.
