### ISSUE TITLE
website logo / title misaligned

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgbackup.github.io#73]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/356103/145808850-a73daef3-5f00-46ba-bd05-3f9a6fac8f0a.png">

Bold green "Borg" letters are hanging out to the left of the bigger black box.

**Comment by ThomasWaldmann** [comment]
Hmm, also happens in Brave browser, which is Chromium based, so guess it is a general problem.

**Comment by ThomasWaldmann** [comment]
Yup, the "hanging out" is fixed.

Now it is left-aligned, not sure if centered inside the black outer box would be maybe prettier?

**Comment by snsmac** [comment]
I opened a new version with the centered logo. Personally I don't have any preference about it being centered or not.

**Comment by ThomasWaldmann** [comment]
Fixed since a while, thanks to @snsmac for fixing it!
