### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by DougInAMug** [borgbackup/borgbackup.github.io#87]
The navbar is a dominant design for navigation. Opting for one would make it more intuitive for people to navigate. It would also be easy to embed it on every page, eliminating the need for a back button on each sub-page. Here is a mockup of what it could look like (design details would need some working)

![Screenshot from 2023-08-17 18-39-15](https://github.com/borgbackup/borgbackup.github.io/assets/13798767/a3e27657-bddf-4ec5-baef-9c4afdcc22fe)

What do you think?

**Comment by ThomasWaldmann** [comment]
Yeah, that's a good idea. Guess the green items on the current main page would go into the menu. The menu might need to adapt to screen width.

**Comment by DougInAMug** [comment]
Closed with #90
