### ISSUE TITLE
Inform people that demos are highlight-able

### ISSUE THREAD

**Issue by DougInAMug** [borgbackup/borgbackup.github.io#88]
I was looking through the CSS to see if things could be minimized, and saw a lot of Asciinema assets. After looking into the project, I understood that the characters can be highlighted! This is very cool, but I was completely unaware, and guess I'm not the only one.

A small info at the top of the page could be enough. A small info at the beginning of each video would be ideal, but not sure if that is possible without re-recording them all.

**Comment by ThomasWaldmann** [comment]
With "highlight-able", do you mean that you can select, copy and paste text from the asciinema casts?

BTW, the casts need to be re-made for borg2 anyway.

**Comment by DougInAMug** [comment]
> With "highlight-able", do you mean that you can select, copy and paste text from the asciinema casts?

Exactly. The new casts could start with exactly that: _"You can select, copy and paste text from this cast!"_

**Comment by DougInAMug** [comment]
Closed with #92
