### ISSUE TITLE
Off-site navigation

### ISSUE THREAD

**Issue by DougInAMug** [borgbackup/borgbackup.github.io#93]
`Docs`, `Community` and `Contribute` all navigate off-site. Wikipedia has a "upper-right-arrow-out-of-box" icon, which is perhaps familiar for many. This is sadly not a UTF8 character.

![Screenshot from 2023-08-30 15-37-15](https://github.com/borgbackup/borgbackup.github.io/assets/13798767/3a3a5351-4215-4d5b-b2a6-3627fd802760)

Additionally, off-site links could be placed to the right hand side.

Also, I wonder if `Contribute` could be removed entirely, and rather add and icon bar to the bottom of the main page? (Along with matrix, IRC, mail list, mastodon, twitter...)

**Comment by ThomasWaldmann** [comment]
I'ld rather like to keep the link list at one place (in the docs).

So guess we can close this now, your PR html code is already online. 🎉

**Comment by DougInAMug** [comment]
Yep, I saw it now :)

OK about the links. I am also quite interested 'information architecture' - how to get people to the place they want to be as fast as possible. That was one of a couple of ideas I've had for the site, but I'll present them as separate issues with a bit more background in time.
