### ISSUE TITLE
Possible small issues

### ISSUE THREAD

**Issue by DougInAMug** [borgbackup/borgbackup.github.io#96]
Looking for feedback on whether these observations are issues or not, and if yes whether the suggested course of action is appropriate:
- `demo` subpage has the same on-page title as the home page. All other subpages have unique titles. Is this intentional, or should the title be change to _"Demo screencasts"_ or something similar?
- `releases` has the page title (i.e. in `<head>`) of _"index.rst"_. I guess this should be changed to _"Releases — BorgBackup"_ for consistency?
- actually, all other page titles of subpages except for demo lack a _"— BorgBackup"_ suffix. Should I add them?
- the on-page title on the home page (i.e. _"Deduplicating archiver with compression and encryption"_) has an html line-break. This makes it look not so great on mobile. Should I try and replicate the effect (i.e. having _"Deduplicating archiver"_ on a line by itself) in another way, or simply remove the `<br>`?

**Comment by ThomasWaldmann** [comment]
Good catch!

- yes, "Borg demos" or "Demo screencasts"
- yes
- yes
- guess you could simply remove the BR

The phrase "Deduplicating archiver with compression and encryption" is also used as short description in the pypi (and maybe also other) packages.
